print("Digite o primeiro valor: ")
primeiro = input("")
print("Digite o segundo valor: ")
segundo = input("")
print("Digite o terceiro valor: ")
terceiro = input("")
quarto = int(primeiro) + int(segundo) + int(terceiro)
print("o valor da soma é: ", quarto)