print("Digite o seu nome: ")
nome = input("")
print ("Digite a sua idade: ")
idade = input("")
print ("Digite a sua altura: ")
altura = input("")
print("Bem-vindo: ", nome)
print("A sua idade atual é: ", idade)
print("A sua altura é: ", altura)